apiVersion: v1
kind: Service
metadata:
  name: etic-microservice-svc
spec:
  type: LoadBalancer
  selector:
    app: etic-microservice
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5000
